services:
  ocr-api:
    container_name: ocr_api
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - '${SERVICE_PORT}'
    ports:
      - '${HOST_PORT}:${SERVICE_PORT}'
    networks:
      ocr:
        aliases:
          - ocr_api